config/routes.rb
Rails.application.routes.draw do
  get 'heartbeats/get_count', to: 'heartbeats#get_count'
  post 'heartbeats/destroy_before', to: 'heartbeats#destroy_before'
  resources :heartbeats
  get 'jobs/index'
  get 'jobs/view'
  resources :contacts
  devise_for :users
  resources :probes
  resources :bilges
  resources :light_controllers do
    get 'config', to: 'light_controllers#get_controller_config' 
    get 'status', to: 'light_controllers#get_controller_status'   
  end
  root 'dashboard#main'
  resources :settings, only: [:index] do
  	
  end
  post 'settings/set_device_id', to: 'settings#set_device_id'
  post 'settings/store_local_config', to: 'settings#store_local_config'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bilge.rb
class Bilge < ApplicationRecord
	def notify_contacts!
		if self.pump_no == 1
			@contacts = Contact.where(bilge_main: true)
		elsif self.pump_no == 2
			@contacts = Contact.where(bilge_backup: true)
		end
		@contacts.each do |contact|
			TwilioTextMessenger.new("Bilge pump updated.", contact.phone).call
		end
	end
end

app/controllers/bilges_controller.rb
class BilgesController < ApplicationController
  # require any kind of change and creation of a measure to come through our authenticated api using HMAC 
  # and we skip the CSRF check for these requests
  before_action :http_basic_authenticate, only: [:create]
  before_action :authenticate_user!, only: [:index, :show, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: [:edit, :update, :destroy, :create]

  before_action :set_bilge, only: [:show, :edit, :update, :destroy]

  # GET /bilges
  # GET /bilges.json
  def index
    @bilges = Bilge.all
  end

  # GET /bilges/1
  # GET /bilges/1.json
  def show
  end

  # GET /bilges/new
  def new
    @bilge = Bilge.new
  end

  # GET /bilges/1/edit
  def edit
  end

  # POST /bilges
  # POST /bilges.json
  def create
    @bilge = Bilge.new(bilge_params)

    respond_to do |format|
      if @bilge.save
        # - need to add multiple contact update here
        @bilge.delay.notify_contacts!
        format.html { redirect_to @bilge, notice: 'Bilge was successfully created.' }
        format.json { render :show, status: :created, location: @bilge }
      else
        format.html { render :new }
        format.json { render json: @bilge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bilges/1
  # PATCH/PUT /bilges/1.json
  def update
    respond_to do |format|
      if @bilge.update(bilge_params)
        format.html { redirect_to @bilge, notice: 'Bilge was successfully updated.' }
        format.json { render :show, status: :ok, location: @bilge }
      else
        format.html { render :edit }
        format.json { render json: @bilge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bilges/1
  # DELETE /bilges/1.json
  def destroy
    @bilge.destroy
    respond_to do |format|
      format.html { redirect_to bilges_url, notice: 'Bilge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bilge
      @bilge = Bilge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bilge_params
      params.require(:bilge).permit(:id, :pump_no, :duration)
    end

    def http_basic_authenticate
      @probe = Probe.find(params[:probe_id])
      # ADD CODE HERE TO SUPPORT HMAC IF CONFIGURED
      authenticate_or_request_with_http_basic do |username, password|
        username == @probe.username && password == @probe.password
      end
    end

    def require_authenticated_api
      # THIS IS OLD and from back when I was using HMAC auth. Particle only supports basic auth
    @current_probe = Probe.find_by_id(ApiAuth.access_id(request))
    logger.info request.raw_post # needed due to a bug in api_auth
    # if a probe could not be found via the access id or the one found did not authenticate with the data in the request
    # fail the call
    if @current_probe.nil? || !ApiAuth.authentic?(request, @current_probe.secret) 
      flash[:error] = "Authentication required"
      redirect_to bilges_url, :status => :unauthorized
    end
  end 
end

app/helpers/bilges_helper.rb
module BilgesHelper
end

app/views/bilges/_form.html.erb
<%= form_with(model: bilge, local: true) do |form| %>
  <% if bilge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bilge.errors.count, "error") %> prohibited this bilge from being saved:</h2>

      <ul>
      <% bilge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bilges/edit.html.erb
<h1>Editing Bilge</h1>

<%= render 'form', bilge: @bilge %>

<%= link_to 'Show', @bilge %> |
<%= link_to 'Back', bilges_path %>

app/views/bilges/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4">Bilges</h1>

<%= area_chart Bilge.group_by_day(:created_at, range: 2.weeks.ago.midnight..Time.now).count, id: "bilge-chart", library: {backgroundColor: "red", borderColor: "#ffffff"} %>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Pump_No</th>
      <th>Duration</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @bilges.each do |bilge| %>
      <tr>
        <td><%= bilge.id %></td>
        <td><%= bilge.pump_no %></td>
        <td><%= bilge.duration %></td>
        <td><%= link_to 'Show', bilge %></td>
        <td><%= link_to 'Edit', edit_bilge_path(bilge) %></td>
        <td><%= link_to 'Destroy', bilge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bilge', new_bilge_path %>

app/views/bilges/new.html.erb
<h1>New Bilge</h1>

<%= render 'form', bilge: @bilge %>

<%= link_to 'Back', bilges_path %>

app/views/bilges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @bilge.id %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @bilge.duration %>
</p>

<%= link_to 'Edit', edit_bilge_path(@bilge) %> |
<%= link_to 'Back', bilges_path %>