config/routes.rb
Rails.application.routes.draw do
  get 'heartbeats/get_count', to: 'heartbeats#get_count'
  post 'heartbeats/destroy_before', to: 'heartbeats#destroy_before'
  resources :heartbeats
  get 'jobs/index'
  get 'jobs/view'
  resources :contacts
  devise_for :users
  resources :probes
  resources :bilges
  resources :light_controllers do
    get 'config', to: 'light_controllers#get_controller_config' 
    get 'status', to: 'light_controllers#get_controller_status'   
  end
  root 'dashboard#main'
  resources :settings, only: [:index] do
  	
  end
  post 'settings/set_device_id', to: 'settings#set_device_id'
  post 'settings/store_local_config', to: 'settings#store_local_config'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/heartbeat.rb
class Heartbeat < ApplicationRecord
  belongs_to :probe
end

app/controllers/heartbeats_controller.rb
class HeartbeatsController < ApplicationController
  before_action :set_heartbeat, only: [:show, :edit, :update, :destroy]
  before_action :http_basic_authenticate, only: [:create]
  protect_from_forgery with: :null_session

  # GET /heartbeats
  # GET /heartbeats.json
  def index
    @heartbeats = Heartbeat.all
  end

  # GET /heartbeats/1
  # GET /heartbeats/1.json
  def show
  end

  # GET /heartbeats/new
  def new
    @heartbeat = Heartbeat.new
  end

  # GET /heartbeats/1/edit
  def edit
  end

  # POST /heartbeats
  # POST /heartbeats.json
  def create
    @heartbeat = Heartbeat.new(heartbeat_params)

    respond_to do |format|
      if @heartbeat.save
        format.html { redirect_to @heartbeat, notice: 'Heartbeat was successfully created.' }
        format.json { render :show, status: :created, location: @heartbeat }
      else
        format.html { render :new }
        format.json { render json: @heartbeat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heartbeats/1
  # PATCH/PUT /heartbeats/1.json
  def update
    respond_to do |format|
      if @heartbeat.update(heartbeat_params)
        format.html { redirect_to @heartbeat, notice: 'Heartbeat was successfully updated.' }
        format.json { render :show, status: :ok, location: @heartbeat }
      else
        format.html { render :edit }
        format.json { render json: @heartbeat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heartbeats/1
  # DELETE /heartbeats/1.json
  def destroy
    @heartbeat.destroy
    respond_to do |format|
      format.html { redirect_to heartbeats_url, notice: 'Heartbeat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_before
    # Destroy all records before a specific date
    #TODO move this to a background job and do it in batches of less than 5000
    @date = params[:date].to_date
    puts @date.to_s
    begin
      @destruction = Heartbeat.where('created_at <= ?', @date)
      @destruction.destroy_all
    rescue
      Rails.logger.error "Something went wrong when trying to do a mass heartbeat destroy_all command"
    else
      @count = Heartbeat.all.count
    end

    render json: { status: "ok", remaining: @count }.to_json
  end


  def get_count
    #Gets a count of Heartbeat records prior to a given date enabling mass deletion
    @date = params[:date].to_date
    puts @date.to_s
    @count = Heartbeat.where('created_at <= ?', @date).count
    render json: @count.to_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_heartbeat
      @heartbeat = Heartbeat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def heartbeat_params
      params.require(:heartbeat).permit(:probe_id, :voltage, :temp, :humid)
    end

    def http_basic_authenticate
      @probe = Probe.find(params[:probe_id])
      # ADD CODE HERE TO SUPPORT HMAC IF CONFIGURED
      authenticate_or_request_with_http_basic do |username, password|
        username == @probe.username && password == @probe.password
      end
    end
end

app/helpers/heartbeats_helper.rb
module HeartbeatsHelper
end

app/views/heartbeats/_form.html.erb
<%= form_with(model: heartbeat, local: true) do |form| %>
  <% if heartbeat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(heartbeat.errors.count, "error") %> prohibited this heartbeat from being saved:</h2>

      <ul>
      <% heartbeat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :probe_id %>
    <%= form.text_field :probe_id %>
  </div>

  <div class="field">
    <%= form.label :voltage %>
    <%= form.text_field :voltage %>
  </div>

  <div class="field">
    <%= form.label :temp %>
    <%= form.text_field :temp %>
  </div>

  <div class="field">
    <%= form.label :humid %>
    <%= form.text_field :humid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/heartbeats/edit.html.erb
<h1>Editing Heartbeat</h1>

<%= render 'form', heartbeat: @heartbeat %>

<%= link_to 'Show', @heartbeat %> |
<%= link_to 'Back', heartbeats_path %>

app/views/heartbeats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Heartbeats</h1>

<table>
  <thead>
    <tr>
      <th>Sensor</th>
      <th>Voltage</th>
      <th>Temp</th>
      <th>Humid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @heartbeats.each do |heartbeat| %>
      <tr>
        <td><%= heartbeat.probe %></td>
        <td><%= heartbeat.voltage %></td>
        <td><%= heartbeat.temp %></td>
        <td><%= heartbeat.humid %></td>
        <td><%= link_to 'Show', heartbeat %></td>
        <td><%= link_to 'Edit', edit_heartbeat_path(heartbeat) %></td>
        <td><%= link_to 'Destroy', heartbeat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Heartbeat', new_heartbeat_path %>

app/views/heartbeats/new.html.erb
<h1>New Heartbeat</h1>

<%= render 'form', heartbeat: @heartbeat %>

<%= link_to 'Back', heartbeats_path %>

app/views/heartbeats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sensor:</strong>
  <%= @heartbeat.probe %>
</p>

<p>
  <strong>Voltage:</strong>
  <%= @heartbeat.voltage %>
</p>

<p>
  <strong>Temp:</strong>
  <%= @heartbeat.temp %>
</p>

<p>
  <strong>Humid:</strong>
  <%= @heartbeat.humid %>
</p>

<%= link_to 'Edit', edit_heartbeat_path(@heartbeat) %> |
<%= link_to 'Back', heartbeats_path %>