config/routes.rb
Rails.application.routes.draw do
  get 'heartbeats/get_count', to: 'heartbeats#get_count'
  post 'heartbeats/destroy_before', to: 'heartbeats#destroy_before'
  resources :heartbeats
  get 'jobs/index'
  get 'jobs/view'
  resources :contacts
  devise_for :users
  resources :probes
  resources :bilges
  resources :light_controllers do
    get 'config', to: 'light_controllers#get_controller_config' 
    get 'status', to: 'light_controllers#get_controller_status'   
  end
  root 'dashboard#main'
  resources :settings, only: [:index] do
  	
  end
  post 'settings/set_device_id', to: 'settings#set_device_id'
  post 'settings/store_local_config', to: 'settings#store_local_config'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/probe.rb
class Probe < ApplicationRecord
	attr_readonly :secret
end

app/controllers/probes_controller.rb
class ProbesController < ApplicationController
  before_action :set_probe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /probes
  # GET /probes.json
  def index
    @probes = Probe.all
  end

  # GET /probes/1
  # GET /probes/1.json
  def show
    @heartbeats = Heartbeat.where(probe_id: @probe.id).last(20).reverse
    # @heartbeats.limit(20)
  end

  # GET /probes/new
  def new
    @probe = Probe.new
  end

  # GET /probes/1/edit
  def edit
  end

  # POST /probes
  # POST /probes.json
  def create
    @probe = Probe.new(probe_params)
    @probe.secret = ApiAuth.generate_secret_key

    respond_to do |format|
      if @probe.save
        format.html { redirect_to @probe, notice: 'Probe was successfully created.' }
        format.json { render :show, status: :created, location: @probe }
      else
        format.html { render :new }
        format.json { render json: @probe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /probes/1
  # PATCH/PUT /probes/1.json
  def update
    respond_to do |format|
      if @probe.update(probe_params)
        format.html { redirect_to @probe, notice: 'Probe was successfully updated.' }
        format.json { render :show, status: :ok, location: @probe }
      else
        format.html { render :edit }
        format.json { render json: @probe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /probes/1
  # DELETE /probes/1.json
  def destroy
    @probe.destroy
    respond_to do |format|
      format.html { redirect_to probes_url, notice: 'Probe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_probe
      @probe = Probe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def probe_params
      params.require(:probe).permit(:name, :secret, :username, :password, :hmac)
    end
end

app/helpers/probes_helper.rb
module ProbesHelper
end

app/views/probes/_form.html.erb
<%= form_with(model: probe, local: true) do |form| %>
  <% if probe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(probe.errors.count, "error") %> prohibited this probe from being saved:</h2>

      <ul>
      <% probe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :secret %>
    <%= @probe.secret %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :hmac %>
    <%= form.check_box :hmac %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/probes/edit.html.erb
<h1>Editing Probe</h1>

<%= render 'form', probe: @probe %>

<%= link_to 'Show', @probe %> |
<%= link_to 'Back', probes_path %>

app/views/probes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Probes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Secret</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @probes.each do |probe| %>
      <tr>
        <td><%= probe.name %></td>
        <td><%= probe.secret %></td>
        <td><%= link_to 'Show', probe %></td>
        <td><%= link_to 'Edit', edit_probe_path(probe) %></td>
        <td><%= link_to 'Destroy', probe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Probe', new_probe_path %>

app/views/probes/new.html.erb
<h1>New Probe</h1>

<%= render 'form', probe: @probe %>

<%= link_to 'Back', probes_path %>

app/views/probes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @probe.name %>
</p>

<p>
  <strong>Secret:</strong>
  <%= @probe.secret %>
</p>

<p>
  <strong>Username:</strong>
  <%= @probe.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @probe.password %>
</p>

<p>
  <strong>Use HMAC:</strong>
  <%= @probe.hmac %>
</p>

<h2>Heartbeats</h2>

<%= line_chart Heartbeat.group_by_hour(:created_at, range: 2.months.ago.midnight..Time.now).average(:temp) %>

<table>
  <thead>
    <tr>
      <th>Probe</th>
      <th>Voltage</th>
      <th>Temp</th>
      <th>Humid</th>
      <th>Timestampe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @heartbeats.each do |heartbeat| %>
      <tr>
        <td><%= heartbeat.probe %></td>
        <td><%= heartbeat.voltage %></td>
        <td><%= heartbeat.temp %></td>
        <td><%= heartbeat.humid %></td>
        <td><%= heartbeat.created_at %></td>
        <td><%= link_to 'Show', heartbeat %></td>
        <td><%= link_to 'Edit', edit_heartbeat_path(heartbeat) %></td>
        <td><%= link_to 'Destroy', heartbeat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_probe_path(@probe) %> |
<%= link_to 'Back', probes_path %>